# PostgreSQL configuration
#   gem install pg
#
#   Ensure the pg gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: aurgi_sample_app_development

test:
  <<: *default
  database: aurgi_sample_app_test

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "aurgi_sample_app_production") %>
  cache:
    <<: *default
    database: <%= ENV.fetch("CACHE_DATABASE_NAME", "aurgi_sample_app_production_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("QUEUE_DATABASE_NAME", "aurgi_sample_app_production_queue") %>
    migrations_paths: db/queue_migrate
