
services:
  postgres:
    image: postgres:16
    env_file:
      - path: .env
        required: false
      - path: .env.development
        required: false
      - path: .env.local
        required: false
      - path: .env.development.local
        required: false
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    env_file:
      - path: .env
        required: false
      - path: .env.development
        required: false
      - path: .env.local
        required: false
      - path: .env.development.local
        required: false
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data

#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    # Overrides default command so things don't shut down after the process ends.
#    command: sleep infinity
#    depends_on:
#      - postgres
#      - redis
#    stdin_open: true
#    tty: true
#    ports:
#      - "3000:3000"
#      - "3200:3200"
#    environment:
#      - PGHOST=postgres
#      - PGUSER=postgres
#      - PGPASSWORD=password
#      - REDIS_URL=redis://redis:6379
#      - PORT=3000
#    volumes:
#      - .:/rails
#      - node_modules:/rails/node_modules

volumes:
  postgres:
  node_modules:
  redis:
